// Fichier: ui/src/config/banks.ts

export const BANK_CONFIG = {
  // ---------- Trading houses / négoce ----------
  ADM: { name: "ADM", color: "#1B5E20", orgType: "trading_house" },
  BPTRADING: { name: "BP Trading", gradient: ["#0054A6", "#00B140"], orgType: "trading_house" },
  BUNGE: { name: "Bunge", color: "#003DA5", orgType: "trading_house" },
  CARGILL: { name: "Cargill", color: "#007A33", orgType: "trading_house" },
  EDFTRADING: { name: "EDF Trading", color: "#FF5F00", orgType: "trading_house" },
  ENGIEGM: { name: "Engie Global Markets", color: "#00AEEF", orgType: "trading_house" },
  GLENCORE: { name: "Glencore", color: "#003366", orgType: "trading_house" },
  GUNVOR: { name: "Gunvor", color: "#006C67", orgType: "trading_house" },
  LDC: { name: "Louis Dreyfus Company", color: "#004B5B", orgType: "trading_house" },
  MABANAFT: { name: "Mabanaft", color: "#D71920", orgType: "trading_house" },
  MERCURIA: { name: "Mercuria", color: "#8A1538", orgType: "trading_house" },
  SHELLTRADING: { name: "Shell Trading", gradient: ["#FFD500", "#E60012"], orgType: "trading_house" },
  TOTALE: { name: "TotalEnergies", gradient: ["#FF4F00", "#00C389"], orgType: "trading_house" },
  TRAFIGURA: { name: "Trafigura", color: "#001B44", orgType: "trading_house" },
  VITOL: { name: "Vitol", color: "#002147", orgType: "trading_house" },

  // ---------- Corporates (finances de groupes non-financiers) ----------
  AIRBUSFIN: { name: "Airbus Finance", color: "#00205B", orgType: "corporate" },
  AIRLIQFIN: { name: "Air Liquide Finance", color: "#0AA0DF", orgType: "corporate" },
  LVMHFIN: { name: "LVMH Finance", color: "#0B1521", orgType: "corporate" },
  SANOFIFIN: { name: "Sanofi Finance", gradient: ["#4F6DB8", "#9FD356"], orgType: "corporate" },

  // ---------- Buy Side (AM/HF) ----------
  AMUNDI: { name: "Amundi", color: "#003A5D", orgType: "buy_side" },
  AXAIM: { name: "Axa IM", gradient: ["#004689", "#E71D36"], orgType: "buy_side" },
  BLACKROCK: { name: "BlackRock", color: "#000000", orgType: "buy_side" },
  DNCA: { name: "DNCA", color: "#003D5C", orgType: "buy_side" },
  FIDELITY: { name: "Fidelity", color: "#D52B1E", orgType: "buy_side" },
  LFDE: { name: "LFDE", color: "#00324E", orgType: "buy_side" },
  PIMCO: { name: "PIMCO", color: "#003A5D", orgType: "buy_side" },
  SYCOMORE: { name: "Sycomore", color: "#006E3A", orgType: "buy_side" },
  WELLINGTON: { name: "Wellington", color: "#003E6B", orgType: "buy_side" },

  // ---------- Vendors / Tech / Exchanges ----------
  BLOOMBERG: { name: "Bloomberg", color: "#000000", orgType: "vendor" },
  CME: { name: "CME Group", color: "#003057", orgType: "vendor" },
  EURONEXT: { name: "Euronext", gradient: ["#0AAE59", "#0A7BC2"], orgType: "vendor" },
  LSEG: { name: "LSEG", color: "#00263E", orgType: "vendor" },
  MUREX: { name: "Murex", color: "#0050A0", orgType: "vendor" },
  SIX: { name: "SIX", color: "#E1251B", orgType: "vendor" },

  // ---------- Assureurs ----------
  AG2R: { name: "AG2R La Mondiale", gradient: ["#3C3C3B", "#00A3DA"], orgType: "insurer" },
  GENERALI: { name: "Generali", color: "#B30838", orgType: "insurer" },
  SCOR: { name: "Scor", color: "#005870", orgType: "insurer" },

  // ---------- Brokers / Interdealer / Prop-MM ----------
  BGCPARTNERS: { name: "BGC Partners", color: "#C80000", orgType: "broker" },
  FLOWTRADERS: { name: "Flow Traders", gradient: ["#000000", "#CC0000"], orgType: "broker" },
  GFI: { name: "GFI Securities", color: "#1A1A1A", orgType: "broker" },
  IMC: { name: "IMC Trading", color: "#0060DF", orgType: "broker" },
  JANESTREET: { name: "Jane Street", color: "#111827", orgType: "broker" },
  KC: { name: "Kepler Cheuvreux", color: "oklch(0.6 0.15 195)", orgType: "broker" },
  MAREX: { name: "Marex", color: "#E4002B", orgType: "broker" },
  OPTIVER: { name: "Optiver", color: "#E2231A", orgType: "broker" },
  SMBCNIKKO: { name: "SMBC Nikko", gradient: ["#006C3B", "#C9A227"], orgType: "broker" },
  STIFEL: { name: "Stifel", color: "#0F2C4C", orgType: "broker" },
  SUSQ: { name: "Susquehanna", color: "#0B3A60", orgType: "broker" },
  TPICAP: { name: "TP Icap", color: "#001A72", orgType: "broker" },

  // ---------- Private banks / WM ----------
  EDR: { name: "Edmond de Rothschild", color: "oklch(0.8067 0.1727 91.59)", orgType: "private_bank" },
  JB: { name: "Julius Baer", gradient: ["oklch(0.4 0.02 240)", "oklch(0.7 0.15 230)"], orgType: "private_bank" },
  LO: { name: "Lombard Odier", gradient: ["oklch(0.25 0.08 260)", "oklch(0.4 0.1 260)"], orgType: "private_bank" },
  MIRABAUD: { name: "Mirabaud", color: "#0F4C81", orgType: "private_bank" },
  PICTET: { name: "Pictet", logo: "/logos/pictet.svg", color: "#00A19B", orgType: "private_bank" },
  ROTHSCHILDANDCO: { name: "Rothschild & Co", gradient: ["oklch(0.35 0.1 260)", "oklch(0.75 0.15 85)"], orgType: "private_bank" },
  VON: { name: "Vontobel", color: "oklch(0.68 0.15 195)", orgType: "private_bank" },

  // ---------- Banks (IB / universelles / retail) ----------
  ALANTRA: { name: "Alantra", color: "#002B45", orgType: "banks" },
  BANCOBRASIL: { name: "Banco Do Brasil", color: "#FFCC00", orgType: "banks" },
  BARCLAYS: { name: "Barclays", color: "oklch(0.75 0.2 210)", orgType: "banks" },
  BBVA: { name: "BBVA", color: "oklch(0.6338 0.1431 64.06)", orgType: "banks" },
  BERENBERG: { name: "Berenberg", color: "#C65E1A", orgType: "banks" },
  BNPP: { name: "BNP Paribas", color: "oklch(0.8 0.15 140)", orgType: "banks" },
  BOFA: { name: "Bank of America", gradient: ["oklch(0.55 0.20 25)", "oklch(0.9 0.02 260)"], orgType: "banks" },
  BOC: { name: "Bank of China", color: "#9D0A0E", orgType: "banks" },
  BPCE: { name: "Groupe BPCE", color: "oklch(0.2868 0.1036 330.88)", orgType: "banks" },
  BRYANGARNIER: { name: "Bryan Garnier", color: "#1E3A5F", orgType: "banks" },
  CA: { name: "Crédit Agricole", color: "oklch(0.75 0.18 145)", orgType: "banks" },
  CAIXABANK: { name: "Caixa Bank", gradient: ["#00B1E6", "#F39200"], orgType: "banks" },
  CIC: { name: "CIC", gradient: ["oklch(0.6 0.2 250)", "oklch(0.7 0.2 150)"], orgType: "banks" },
  CITI: { name: "Citi", color: "oklch(0.62 0.20 250)", orgType: "banks" },
  DB: { name: "Deutsche Bank", color: "oklch(0.7 0.15 260)", orgType: "banks" },
  DZBANK: { name: "DZ Bank", color: "#00589C", orgType: "banks" },
  GOLDMANSACHS: { name: "Goldman Sachs", color: "#4A84C4", orgType: "banks" },
  HSBC: { name: "HSBC", gradient: ["oklch(0.6 0.28 25)", "oklch(0.95 0.05 20)"], orgType: "banks" },
  ICBC: { name: "ICBC", color: "#C00000", orgType: "banks" },
  ING: { name: "ING", gradient: ["oklch(0.7 0.25 55)", "oklch(0.8 0.2 60)"], orgType: "banks" },
  INTESASANPAOLO: { name: "Intesa Sanpaolo", gradient: ["#007D3E", "#F37021"], orgType: "banks" },
  JEFFERIES: { name: "Jefferies", color: "#00529B", orgType: "banks" },
  JPM: { name: "JP Morgan", color: "#2D4A63", orgType: "banks" },
  KFW: { name: "KfW Bank", color: "#003063", orgType: "banks" },
  LBP: { name: "La Banque Postale", gradient: ["#003399", "#FFC300"], orgType: "banks" },
  MS: { name: "Morgan Stanley", gradient: ["oklch(0.4 0.15 260)", "oklch(0.6 0.2 250)"], orgType: "banks" },
  MIZUHO: { name: "Mizuho", color: "#1A2274", orgType: "banks" },
  MUFG: { name: "MUFG", gradient: ["oklch(0.4 0.01 0)", "oklch(0.6 0.28 25)"], orgType: "banks" },
  NATIXIS: { name: "Natixis", gradient: ["#4B306A", "#A38BB1"], orgType: "banks" },
  NOMURA: { name: "Nomura", color: "#E60028", orgType: "banks" },
  ODDO: { name: "Oddo BHF", color: "oklch(0.6338 0.1357 175.24)", orgType: "banks" },
  RABOBANK: { name: "Rabobank", color: "#001090", orgType: "banks" },
  RBC: { name: "RBC", gradient: ["oklch(0.5 0.2 265)", "oklch(0.9 0.25 90)"], orgType: "banks" },
  SANTANDER: { name: "Santander", color: "#EC0000", orgType: "banks" },
  SG: { name: "Société Générale", color: "oklch(0.7 0.18 15)", orgType: "banks" },
  STANCHART: { name: "Standard Chartered", gradient: ["#00A39B", "#0072CE"], orgType: "banks" },
  UBS: { name: "UBS", gradient: ["oklch(0.0044 0.0074 91.59)", "oklch(0.3 0.1 15)"], orgType: "banks" },
  UNICREDIT: { name: "UniCredit", color: "#E30035", orgType: "banks" },
  WELLSFARGO: { name: "Wells Fargo", color: "#D71E28", orgType: "banks" },
};

// Liste plate utilisée par l’UI
export const BANKS_LIST = Object.entries(BANK_CONFIG).map(([key, value]) => ({
  id: key,
  ...value,
}));
