export const BANK_LOGO_DOMAINS: Record<string, string> = {
  ADM: "adm.com",
  AG2R: "ag2rlamondiale.fr",
  AIRBUSFIN: "airbus.com",
  AIRLIQFIN: "airliquide.com",
  ALANTRA: "alantra.com",
  AMUNDI: "amundi.com",
  AXAIM: "axa-im.com",
  BANCOBRASIL: "bb.com.br",
  BARCLAYS: "barclays.com",
  BOC: "bankofchina.com",
  BOFA: "bankofamerica.com",
  BBVA: "bbva.com",
  BERENBERG: "berenberg.com",
  BGCPARTNERS: "bgcpartners.com",
  BLACKROCK: "blackrock.com",
  BLOOMBERG: "bloomberg.com",
  BNPP: "bnpparibas.com",
  BPCE: "groupebpce.com",
  BPTRADING: "bp.com",
  BRYANGARNIER: "bryangarnier.com",
  BUNGE: "bunge.com",
  CA: "credit-agricole.com",
  CAIXABANK: "caixabank.com",
  CANTOR: "cantor.com",
  CARGILL: "cargill.com",
  CIC: "cic.fr",
  CITI: "citi.com",
  CME: "cmegroup.com",
  DB: "db.com",
  DNCA: "dnca-investments.com",
  DZBANK: "dzbank.com",
  EDFTRADING: "edftrading.com",
  EDR: "edmond-de-rothschild.com",
  ENGIEGM: "engie.com",
  EURONEXT: "euronext.com",
  FIDELITY: "fidelity.com",
  FLOWTRADERS: "flowtraders.com",
  GENERALI: "generali.com",
  GFI: "gfigroup.com",
  GLENCORE: "glencore.com",
  GOLDMANSACHS: "gs.com",
  GUNVOR: "gunvorgroup.com",
  HSBC: "hsbc.com",
  ICBC: "icbc.com.cn",
  IMC: "imc.com",
  ING: "ing.com",
  INTESASANPAOLO: "intesasanpaolo.com",
  JANESTREET: "janestreet.com",
  JB: "juliusbaer.com",
  JEFFERIES: "jefferies.com",
  JPM: "jpmorganchase.com",
  KC: "keplercheuvreux.com",
  KFW: "kfw.de",
  LBP: "labanquepostale.fr",
  LFDE: "lfde.com",
  LDC: "ldc.com",
  LO: "lombardodier.com",
  LSEG: "lseg.com", // <-- AJOUTÉ
  LVMHFIN: "lvmh.com",
  MABANAFT: "mabanaft.com",
  MAREX: "marex.com",
  MERCURIA: "mercuria.com",
  MIRABAUD: "mirabaud.com",
  MIZUHO: "mizuho-fg.com",
  MS: "morganstanley.com",
  MUFG: "mufg.jp",
  MUREX: "murex.com", // <-- AJOUTÉ
  NATIXIS: "natixis.com",
  NOMURA: "nomura.com",
  ODDO: "oddobhf.com",
  OPTIVER: "optiver.com",
  PICTET: "pictet.com",
  PIMCO: "pimco.com",
  RABOBANK: "rabobank.com",
  RBC: "rbc.com",
  ROTHSCHILDANDCO: "rothschildandco.com",
  SANOFIFIN: "sanofi.com",
  SANTANDER: "santander.com",
  SCOR: "scor.com",
  SG: "societegenerale.com",
  SHELLTRADING: "shell.com",
  SIX: "six-group.com",
  SMBCNIKKO: "smbcnikko.co.jp",
  STANCHART: "sc.com",
  STIFEL: "stifel.com",
  SUSQ: "sig.com", // Susquehanna (SIG)
  SYCOMORE: "sycomore-am.com",
  TOTALE: "totalenergies.com",
  TPICAP: "tpicap.com",
  TRAFIGURA: "trafigura.com",
  UBS: "ubs.com",
  UNICREDIT: "unicreditgroup.eu",
  VITOL: "vitol.com",
  VON: "vontobel.com",
  WELLINGTON: "wellington.com",
  WELLSFARGO: "wellsfargo.com",
};

// alias -> clé canonique
const BANK_LOGO_ALIASES: Record<string, string> = {
  BOFA_MAIN: "BOFA",
  BOFA_STUDENTS: "BOFA",
  BAML: "BOFA",
};

const norm = (s?: string) => (s ?? "").toUpperCase().replace(/[^A-Z0-9]/g, "");

export function getBankLogoUrl(source?: string): string | undefined {
  const key = norm(source);
  const mapped = BANK_LOGO_ALIASES[key] ?? key;
  const domain = BANK_LOGO_DOMAINS[mapped];
  return domain ? `https://logo.clearbit.com/${domain}` : undefined;
}